apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-dp
  namespace: snake-game
  labels:
    app: snake-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      namespace: snake-game
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake-game
        image: softconsist/snake-game:24
        ports:
        - containerPort: 80

